import Image from "next/image";

export const metadata = {
  title: "AI Debate Coach - Sharpen Your Critical Thinking",
  description:
    "Master logical reasoning, detect fallacies, and build stronger arguments with AI-powered debate exercises.",
};

export default function DebateCoachApp() {
  return (
    <div>
      <section className="hero">
        <span className="btn-pill">iOS App</span>
        <h2>
          <span className="hero-accent">AI Debate Coach</span>
        </h2>
        <p>Sharpen Your Mind, Strengthen Your Arguments</p>
        <div className="download-badges">
          <a
            href="https://apps.apple.com/app/ai-debate-coach"
            className="store-badge"
            aria-label="Download on the App Store"
          >
            <Image
              src="/app-store.png"
              alt="Download on the App Store"
              width={170}
              height={50}
              style={{ height: "auto" }}
            />
          </a>
        </div>
      </section>

      <section className="app-card">
        <h3>About AI Debate Coach</h3>
        <p>
          AI Debate Coach is your personal critical thinking trainer. Through
          quick, tap-based exercises powered by AI, you&apos;ll learn to spot
          logical fallacies, evaluate argument strength, and think more clearly
          — all in just a few minutes a day. No typing required: simply read,
          tap, and learn.
        </p>
      </section>

      <section className="features-grid">
        <div className="feature-item">
          <div className="feature-icon">🔍</div>
          <h4>Fallacy Detection</h4>
          <p>
            Read AI-generated arguments and identify logical fallacies like ad
            hominem, straw man, false dilemma, and more
          </p>
        </div>
        <div className="feature-item">
          <div className="feature-icon">⚖️</div>
          <h4>Argument Analysis</h4>
          <p>
            Compare three arguments and pick the strongest one based on evidence,
            reasoning, and impact
          </p>
        </div>
        <div className="feature-item">
          <div className="feature-icon">🧠</div>
          <h4>AI-Powered Exercises</h4>
          <p>
            Every exercise is uniquely generated by AI, so you never see the same
            content twice
          </p>
        </div>
        <div className="feature-item">
          <div className="feature-icon">📊</div>
          <h4>Skill Radar</h4>
          <p>
            Track your progress across five dimensions: logic, evidence,
            critical thinking, pattern recognition, and argument structure
          </p>
        </div>
        <div className="feature-item">
          <div className="feature-icon">🔥</div>
          <h4>Daily Streaks</h4>
          <p>
            Build a practice habit with streak tracking, daily challenges, and
            progress history
          </p>
        </div>
        <div className="feature-item">
          <div className="feature-icon">⚡</div>
          <h4>Quick Sessions</h4>
          <p>
            Each exercise takes about 5 minutes — perfect for a commute, a
            break, or before bed
          </p>
        </div>
      </section>

      <section className="app-card">
        <h3>How It Works</h3>
        <div className="features-grid">
          <div className="feature-item">
            <div className="feature-icon">1️⃣</div>
            <h4>Pick a Topic</h4>
            <p>
              Choose from dozens of debate topics across politics, technology,
              ethics, and more — or create your own
            </p>
          </div>
          <div className="feature-item">
            <div className="feature-icon">2️⃣</div>
            <h4>Read & Decide</h4>
            <p>
              The AI generates arguments for you to analyze. Tap your answer —
              no typing needed
            </p>
          </div>
          <div className="feature-item">
            <div className="feature-icon">3️⃣</div>
            <h4>Learn Instantly</h4>
            <p>
              Get immediate feedback with detailed explanations of why an
              argument is strong or where the fallacy lies
            </p>
          </div>
          <div className="feature-item">
            <div className="feature-icon">4️⃣</div>
            <h4>Track Growth</h4>
            <p>
              Watch your skill radar evolve as you complete exercises and
              sharpen your reasoning abilities
            </p>
          </div>
        </div>
      </section>

      <section className="app-card">
        <h3>Coming Soon</h3>
        <p>
          We&apos;re actively developing new exercise types to push your
          debating skills even further:
        </p>
        <div className="features-grid">
          <div className="feature-item">
            <div className="feature-icon">🎤</div>
            <h4>Voice Mode</h4>
            <p>
              Practice speaking your arguments aloud with real-time speech
              recognition and AI analysis of your delivery
            </p>
          </div>
          <div className="feature-item">
            <div className="feature-icon">✍️</div>
            <h4>Argument Building</h4>
            <p>
              Construct your own arguments step by step — claim, evidence,
              warrant, impact — and get AI scoring on each component
            </p>
          </div>
          <div className="feature-item">
            <div className="feature-icon">🗣️</div>
            <h4>Live AI Debates</h4>
            <p>
              Debate against an AI opponent in real time with text or voice,
              and receive a full performance breakdown afterward
            </p>
          </div>
          <div className="feature-item">
            <div className="feature-icon">💡</div>
            <h4>Counterargument Drills</h4>
            <p>
              Read an AI position and craft a rebuttal — train yourself to
              think on your feet and respond to any argument
            </p>
          </div>
        </div>
      </section>

      <section className="app-card">
        <h3>Premium Features</h3>
        <p>
          AI Debate Coach is free to get started. Upgrade to Premium to unlock
          the full experience:
        </p>
        <ul style={{ marginLeft: "2rem", marginBottom: "1rem" }}>
          <li>Unlimited topics and custom topic creation</li>
          <li>Intermediate and Advanced difficulty levels</li>
          <li>Unlimited daily exercises (free tier: 3 per day)</li>
          <li>All upcoming exercise types as they launch</li>
        </ul>
      </section>

      <section className="contact-info">
        <h3>Support & Contact</h3>
        <p>
          Have questions about AI Debate Coach? We&apos;d love to hear from you.
          <br />
          <a href="mailto:contact@easytech-agency.net">
            contact@easytech-agency.net
          </a>
        </p>
      </section>

      <div className="section-divider"></div>

      <section className="app-card">
        <h3>Legal Information</h3>
        <p>
          Review our legal documents to learn more about our privacy policy and
          terms of use.
        </p>
        <div className="app-links">
          <a href="/privacy/debate-coach" className="btn btn-secondary">
            Privacy Policy
          </a>
          <a href="/terms/debate-coach" className="btn btn-secondary">
            Terms of Use
          </a>
        </div>
      </section>
    </div>
  );
}
