import Link from "next/link";

export const metadata = {
  title: "Terms of Use - AI Spiritual Readings",
  description:
    "Terms of Use for the AI Spiritual Readings application by EasyTech Agency",
};

export default function AISpiritualReadingsTerms() {
  return (
    <div className="legal-content">
      <h1>Terms of Use - AI Spiritual Readings</h1>
      <p>
        <strong>Last updated:</strong> March 12, 2026
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        {`By downloading, installing, or using the AI Spiritual Readings
        application ("the App"), you agree to be bound by these Terms of Use
        ("Terms"). If you do not agree to these Terms, do not use the App.`}
      </p>

      <h2>2. Description of Service</h2>
      <p>
        {`AI Spiritual Readings is a mobile application that uses artificial
        intelligence to provide spiritual readings and guidance. Features include
        tarot card readings, daily horoscope forecasts, AI-powered palm reading
        via photo analysis, numerology calculations and interpretations, angel
        number lookups, and daily cosmic guidance. All readings are generated
        using AI and are intended for entertainment and personal reflection
        purposes only.`}
      </p>

      <h2>3. License</h2>
      <p>
        {`EasyTech Agency grants you a limited, non-exclusive, non-transferable,
        and revocable license to use the App for personal, non-commercial
        purposes in accordance with these Terms.`}
      </p>

      <h2>4. Subscriptions and Purchases</h2>
      <p>
        {`AI Spiritual Readings offers both free and premium features. Premium
        features are accessible through a paid subscription:`}
      </p>
      <ul style={{ marginLeft: "2rem", marginBottom: "1rem" }}>
        <li>Prices are displayed in the App and may vary by region</li>
        <li>Subscriptions renew automatically unless cancelled</li>
        <li>
          You may cancel your subscription at any time through your Apple
          account settings
        </li>
        <li>
          {`Refunds are handled in accordance with Apple's policies`}
        </li>
        <li>
          Free users have access to basic features; premium features such as
          palm reading and Celtic Cross spread require a subscription
        </li>
      </ul>

      <h2>5. AI-Generated Content</h2>
      <p>
        {`The App uses artificial intelligence to generate spiritual readings,
        horoscopes, interpretations, and guidance. You acknowledge and agree
        that:`}
      </p>
      <ul style={{ marginLeft: "2rem", marginBottom: "1rem" }}>
        <li>
          All readings are generated by AI and are for entertainment and
          personal reflection purposes only
        </li>
        <li>
          Readings do not predict the future and should not be relied upon for
          making important life decisions
        </li>
        <li>
          AI-generated content is not a substitute for professional advice —
          medical, financial, legal, or psychological
        </li>
        <li>
          Palm reading does not diagnose medical conditions or predict health
          outcomes
        </li>
        <li>
          Horoscope forecasts are generalized guidance, not guaranteed
          predictions
        </li>
        <li>
          EasyTech Agency does not guarantee the accuracy or suitability of any
          AI-generated reading for any particular purpose
        </li>
        <li>
          Readings may vary each time they are generated, even with the same
          inputs
        </li>
      </ul>

      <h2>6. Photos and Camera Usage</h2>
      <p>
        {`The App uses your device camera for the palm reading feature. By using
        this feature, you acknowledge that:`}
      </p>
      <ul style={{ marginLeft: "2rem", marginBottom: "1rem" }}>
        <li>
          Palm photos you take are sent to our servers for AI analysis
        </li>
        <li>
          You are solely responsible for the photos you take and upload
        </li>
        <li>
          You should only take photos of your own palm or palms for which you
          have the owner&apos;s consent
        </li>
        <li>
          Photos are processed in real-time and are not permanently stored on
          our servers
        </li>
        <li>We do not use your photos to train AI models</li>
        <li>
          Camera access can be revoked at any time in your device settings
        </li>
      </ul>

      <h2>7. User Content and Intellectual Property</h2>
      <p>
        {`When you provide questions, prompts, or photos to generate readings, you
        retain ownership of your input content. Regarding AI-generated
        readings:`}
      </p>
      <ul style={{ marginLeft: "2rem", marginBottom: "1rem" }}>
        <li>
          You may use AI-generated readings for personal purposes (e.g.,
          journaling, sharing with friends)
        </li>
        <li>
          You may not sell, license, or commercially distribute AI-generated
          readings
        </li>
        <li>
          The App, its codebase, AI models, algorithms, and branding are the
          property of EasyTech Agency and are protected by intellectual property
          laws
        </li>
      </ul>

      <h2>8. Acceptable Use</h2>
      <p>You agree to:</p>
      <ul style={{ marginLeft: "2rem", marginBottom: "1rem" }}>
        <li>Use the App in accordance with its intended purpose</li>
        <li>
          Not submit prompts intended to generate inappropriate, offensive, or
          illegal content
        </li>
        <li>
          Not attempt to reverse-engineer the AI models, algorithms, or service
          infrastructure
        </li>
        <li>
          Not upload photos containing inappropriate content or content that
          violates the rights of others
        </li>
        <li>Respect all intellectual property rights</li>
        <li>
          Not attempt to compromise the security of the App or its services
        </li>
        <li>
          Not use automated tools, bots, or scripts to interact with the App
        </li>
      </ul>

      <h2>9. Disclaimers</h2>
      <p>
        {`The App is provided "as is" without warranty of any kind. Specifically:`}
      </p>
      <ul style={{ marginLeft: "2rem", marginBottom: "1rem" }}>
        <li>
          All spiritual readings are for entertainment and personal reflection
          only
        </li>
        <li>
          The App does not provide medical, psychological, financial, or legal
          advice
        </li>
        <li>
          Palm reading analysis is based on AI pattern recognition and
          traditional palmistry symbolism — it does not diagnose medical
          conditions
        </li>
        <li>
          We do not guarantee the availability or uptime of AI generation
          services
        </li>
        <li>
          EasyTech Agency is not responsible for any decisions made based on
          readings generated by the App
        </li>
      </ul>

      <h2>10. Limitation of Liability</h2>
      <p>
        {`In no event shall EasyTech Agency be liable for any indirect, incidental,
        special, or consequential damages arising from your use of the App,
        including but not limited to decisions made based on AI-generated
        readings, loss of data, or service interruptions.`}
      </p>

      <h2>11. Termination</h2>
      <p>
        {`We may terminate or suspend your access to the App at any time, without
        notice, for any reason, including if you violate these Terms. Upon
        termination, your right to use the App ceases immediately. You may
        request deletion of your data by contacting us.`}
      </p>

      <h2>12. Changes to Terms</h2>
      <p>
        {`We reserve the right to modify these Terms at any time. Changes will
        take effect upon publication in the App. Continued use of the App after
        changes constitutes acceptance of the updated Terms.`}
      </p>

      <h2>13. Governing Law</h2>
      <p>
        {`These Terms are governed by French law. Any dispute shall be subject to
        the exclusive jurisdiction of the French courts.`}
      </p>

      <h2>14. Contact</h2>
      <p>
        For any questions regarding these Terms of Use, contact us at:
        <br />
        <a href="mailto:contact@easytech-agency.net">
          contact@easytech-agency.net
        </a>
      </p>

      <div style={{ marginTop: "3rem", textAlign: "center" }}>
        <Link href="/apps/ai-spiritual-readings" className="btn">
          Back to AI Spiritual Readings
        </Link>
      </div>
    </div>
  );
}
